version: 2
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Validate terraform code
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
