name: Release Drafter

on:
  push:
    branches:
    - release-drafter # for testing edits to configuration

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'acemod/ACEX'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
